// <auto-generated />
namespace WindowsFormsApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class patient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patient));
        
        string IMigrationMetadata.Id
        {
            get { return "202012031344072_patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
